### ISSUE TITLE
small problems

### ISSUE THREAD

**Issue by GopherJ** [casbin-rs/actix-casbin-auth#13]
1. remove the following `unwrap`
    https://github.com/casbin-rs/actix-casbin-auth/blob/31e68086822c4437b6a10729fb3868837eec7110/src/middleware.rs#L38

2. change to sync function, async will has at least 100ns's overhead
    https://github.com/casbin-rs/actix-casbin-auth/blob/31e68086822c4437b6a10729fb3868837eec7110/src/middleware.rs#L44

3. change to sync function
    https://github.com/casbin-rs/actix-casbin-auth/blob/31e68086822c4437b6a10729fb3868837eec7110/src/middleware.rs#L48

**Comment by hackerchai** [comment]
Fixed in #19
