### ISSUE TITLE
maybe `enforce_mut()` should be used?

### ISSUE THREAD

**Issue by sify21** [casbin-rs/actix-casbin-auth#16]
An enforcer is put in an `Arc<RwLock<>>` and is write-locked before use. But `enforce()` method takes an immutable reference, it doesn't need to be locked. Maybe enforce_mut should be used? https://github.com/casbin/casbin-rs/blob/c88f13cb59a428b05a4f9b03e83f3f5bea36dd78/src/cached_enforcer.rs#L233

**Comment by GopherJ** [comment]
@hackerchai this is urgent, could you do it?

**Comment by hackerchai** [comment]
> @hackerchai this is urgent, could you do it?

@GopherJ  I will have a try.

**Comment by hackerchai** [comment]
> An enforcer is put in an `Arc<RwLock<>>` and is write-locked before use. But `enforce()` method takes an immutable reference, it doesn't need to be locked. Maybe enforce_mut should be used? https://github.com/casbin/casbin-rs/blob/c88f13cb59a428b05a4f9b03e83f3f5bea36dd78/src/cached_enforcer.rs#L233

@sify21 Thanks for the advise. But unfortunately, both `Enforcer` and `CachedEnforcer` are not `sync` at present. When we are using actix middleware, we have to do modification to the `CachedEnforcer` and the middleware is multi-threading. So we can't wrap the `CachedEnforcer` with `Arc`. For now, we can only use `Arc<Mutex<CachedEnforcer>>` or `Arc<RwLock<CachedEnforcer>>` to ensure the safety. In future, we plan to implement the `sync enforcer` to avoid the usage of lock.

**Comment by sify21** [comment]
I see. Then currently with the `RwLock`, we should change to `enforce_mut` to utilize the cache
