### ISSUE TITLE
no default features for actix-web

### ISSUE THREAD

**Issue by robjtede** [casbin-rs/actix-casbin-auth#23]
If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:

```diff
- actix-web = "3.0.2"
+ actix-web = { version = "3.0.2", default-features = false }
```

**Comment by hsluoyz** [comment]
@hackerchai

/cc @GopherJ

**Comment by hackerchai** [comment]
> If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:
> 
> ```diff
> - actix-web = "3.0.2"
> + actix-web = { version = "3.0.2", default-features = false }
> ```

@robjtede Can you  make a PR?

**Comment by hackerchai** [comment]
> 
> If/when the actix-web dependency is updated to v3, the dependency in Cargo.toml should ideally be:
> 
> ```diff
> - actix-web = "3.0.2"
> + actix-web = { version = "3.0.2", default-features = false }
> ```

@robjtede Working on this

**Comment by hackerchai** [comment]
@robjtede  see #24

**Comment by hsluoyz** [comment]
Released: https://github.com/casbin-rs/actix-casbin-auth/releases/tag/v0.4.4
