### ISSUE TITLE
Actix with diesel and self Auth middlewaze

### ISSUE THREAD

**Issue by vietlib** [casbin-rs/actix-casbin-auth#3]
Can you create an example for Casbin Middlewaze with Model and Policy get from Postgres (Diesel) and self Auth please ?

**Comment by hsluoyz** [comment]
@GopherJ @xcaptain @hackerchai

**Comment by hackerchai** [comment]
> Can you create an example for Casbin Middlewaze with Model and Policy get from Postgres (Diesel) and self Auth please ?

I am working on it. I will ping you when it is finished.

**Comment by hackerchai** [comment]
> Can you create an example for Casbin Middlewaze with Model and Policy get from Postgres (Diesel) and self Auth please ?

We recommend using [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter) rather than diesel-adapter, because the sqlx-adapter is fully async. The demo will use sqlx-adapter and diesel(for app data) with PostgreSQL. We will also implement a JWT authentication middleware working with actix-casbin-auth.

**Comment by GopherJ** [comment]
@vietlib Sure, @hackerchai  When you finish the example we can put in actix-web's casbin example and also casbin-rs's example directory

**Comment by hackerchai** [comment]
> @vietlib Sure, @hackerchai  When you finish the example we can put in actix-web's casbin example and also casbin-rs's example directory

Get it

**Comment by vietlib** [comment]
> > Can you create an example for Casbin Middlewaze with Model and Policy get from Postgres (Diesel) and self Auth please ?
> 
> We recommend using [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter) rather than diesel-adapter, because the sqlx-adapter is fully async. The demo will use sqlx-adapter and diesel(for app data) with PostgreSQL. We will also implement a JWT authentication middleware working with actix-casbin-auth.

It's great if you can create full example on an app with postgres authentication and casbin-postgres Model.
Example like: user group must login to post an article and admin can publish it .
It so great ! Thank you so much !

**Comment by vietlib** [comment]
Any update on thiss please

**Comment by hsluoyz** [comment]
@GopherJ @hackerchai

**Comment by hackerchai** [comment]
> Any update on thiss please

See https://github.com/casbin-rs/examples/tree/master/actix-middleware-example

Thanks for your waiting

**Comment by hsluoyz** [comment]
Any one working on it? @GopherJ @hackerchai @PsiACE

**Comment by hackerchai** [comment]
> Any one working on it? @GopherJ @hackerchai @PsiACE 

@hsluoyz Already done. I will close this issue.

**Comment by hsluoyz** [comment]
Great, thanks!

**Comment by makorne** [comment]
> We recommend using [sqlx-adapter](https://github.com/casbin-rs/sqlx-adapter) rather than diesel-adapter, because the sqlx-adapter is fully async. The demo will use sqlx-adapter and diesel(for app data) with PostgreSQL. We will also implement a JWT authentication middleware working with actix-casbin-auth.

Looks like  the sqlx-adapter  is forgotten.
Only
`diesel-adapter = { version = "0.8.1", default-features = false, features = ["postgres","runtime-async-std"] }`

**Comment by hsluoyz** [comment]
@hackerchai @smrpn
