### ISSUE TITLE
Please update to latest casbin crate.

### ISSUE THREAD

**Issue by wt** [casbin-rs/actix-casbin-auth#41]
The newest casbin crate appears to be version 2.2.0. Can you please update that (and maybe other deps) in this package?

**Comment by hsluoyz** [comment]
Hi @wt , can you make a PR for it?

**Comment by wt** [comment]
I'll do it when I can. I am troubleshooting a different issue right now that doesn't seem to be fixed by updating the library. I am trying to figure out if it's a casbin-rs thing or if the problem is in the middleware.
