### ISSUE TITLE
enforcer: Arc<RwLock<CachedEnforcer>>  why use lock？

### ISSUE THREAD

**Issue by tyjyhapple** [casbin-rs/actix-casbin-auth#7]
enforcer: Arc<RwLock<CachedEnforcer>> why  use lock，When I test the performance, the performance drops dramatically under using Rwlock

**Comment by hsluoyz** [comment]
@GopherJ @xcaptain @hackerchai

**Comment by GopherJ** [comment]
@tyjyhapple Sorry for the late reply, I believe we can remove the lock only if we can ensure there is no modification on policies.

In this case we can use only `Arc`

**Comment by hsluoyz** [comment]
Closed as stale.
